### ISSUE TITLE
Usage without ROS

### ISSUE THREAD

**Issue by CanCanZeng** [personalrobotics/OpenChisel#24]
Hi,  @mklingen thank you for openning this nice work!
I have tested the code with ROS, it runs well. But I don't want to use ROS, it's too heavy and I'm not familiar with ROS, can I use openChisel without it? I'm trying to use chisel directly， the code compiled successfully, but did not reconstruct any thing, bellow is its output:

`CHISEL: Done with scan without color
0 chunks 0meshes before collect.0 chunks 0meshes after collect.CHISEL: Integrating a scan`

Is there any tip or demo for me, thanks.

**Comment by dbadrian** [comment]
Also interested in this, any progress already @CanCanZeng ?

**Comment by CanCanZeng** [comment]
@dbadrian Not yet, I turn to use fastfusion opened by tum now,  I find that fastfuion is easier to use and can produce comparable result, you can try it.

**Comment by mklingen** [comment]
You'll have to provide source code to determine what could be going on. Could be a number of things from having the transform of the camera wrong, to malformatted depth data, to incorrectly setup chunks.

Aside: I haven't maintained this project since 2015. If you want something similar I recommend [voxblox](https://github.com/ethz-asl/voxblox) from ETH zurich, which is the spiritual successor of chisel.

**Comment by CanCanZeng** [comment]
@mklingen Thank you for your reply, I will try voxbloc later.

**Comment by shadowver** [comment]
I know it is not relevant, but since it was mentioned that I have also tried Fastfusion. It works well but required quite a quality of depth otherwise it will fail =(. Dont think voxblox has Off_ROS version yet, but you may try to migrate which is what I am trying to do now.
